#<% require 'kitchen-sync' %>
#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: test/fixtures/environments
  roles_path: test/fixtures/roles
  data_bags_path: test/fixtures/data_bags
  client_rb:
    environment: testkitchen

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: test_w_mysql
    run_list:
      - role[w_common_role]
      - role[w_mysql_role]
